core/urls.py
from django.contrib import admin
from django.urls import include, path
from core import views
from core.views import home, manual,error_404
from django.conf.urls import handler404, handler500
urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home, name='home'),
    path('registro/', include('registro.urls')),
    path('servicio/',include('servicios.urls')),
    path('factura/',include("facturacion.urls")),
    path('manual', views.manual, name=''), 
    path('backup/', views.backup, name = 'backup'),
    
]
handler404 = 'core.views.error_404'

servicios/urls.py
from django.urls import path
from servicios.views import editarInsumo, editarMarca, editarServicio, eliminarInsumo, eliminarMarca, eliminarServicio, insumo, marca, servicio
urlpatterns = [
    path('servicio/',servicio, name='servicio'),
    path ('insumo/', insumo, name='insumo'),
    path ('marca/', marca, name='marca'),
    
     #EDITAR Y ELIMINAR MARCA
    path ('marca/editarMarca/<int:id>', editarMarca, name='editarMarca'),
    path ('marca/eliminarMarca/<int:id>', eliminarMarca, name='eliminarMarca'),
    path ('insumo/eliminarInsumo/<int:id>', eliminarInsumo, name='eliminarInsumo'),
    path ('insumo/editarInsumo/<int:id>', editarInsumo, name='editarInsumo'),
    path ('servicio/eliminarServicio/<int:id>', eliminarServicio, name='eliminarServicio'),
    path ('servicio/editarServicio/<int:id>', editarServicio, name='editarServicio'),
]

servicios/models.py
from unicodedata import decimal
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator


class Servicio(models.Model):
    class Tipodeservicio (models.TextChoices):
        LATONERIA = 'Latoneria', _('Latoneria')
        PINTURA= 'Pintura', _('Pintura')
    tipodeservicio = models.CharField(max_length=10, choices=Tipodeservicio.choices, verbose_name=u"Seleccione el tipo de servicio")
    v_trabajo = models.IntegerField(default=0)
    
class Marca(models.Model):
    nombre= models.CharField(max_length=45, blank=False, unique= False, verbose_name=u"Nombre")    
    def __str__(self) -> str:
            return '%s'%(self.nombre)
class Insumo(models.Model):
    nombre = models.CharField(max_length=45, blank=False, unique= False, verbose_name=u"Nombre")
    cantidad= models.PositiveIntegerField(validators=[MinValueValidator(1)])
    precioUnitario= models.IntegerField(default='0', verbose_name="Precio")
    marca=models.ForeignKey(Marca,on_delete=models.SET_NULL, null=True,verbose_name=u"Marca")

    def __str__(self) -> str:
            return '%s %s'%(self.nombre, self.cantidad)

servicios/forms.py
from django import forms

from servicios.models import Insumo, Marca, Servicio

class ServicioForm(forms.ModelForm):
    class Meta:
        model= Servicio
        fields='__all__' 
        #fields= '__all__'
        
class InsumoForm(forms.ModelForm):
    class Meta:
        model = Insumo
        fields='__all__' 
        
        #fields = '__all__'
        
class MarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields='__all__' 
        #fields = '__all__'
    

servicios/views.py
from django.shortcuts import render,redirect
from servicios.forms import  InsumoForm, MarcaForm, ServicioForm
from servicios.models import Insumo, Marca, Servicio
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
@login_required(login_url='/login/')
def servicio(request):
    servicio_db = Servicio.objects.all()
   
    servicio = ServicioForm(request.POST or None, request.FILES or None)

    if servicio.is_valid():
       servicio.save()
       return redirect('servicio')
   
    context = {
        'servicio_db': servicio_db,
        'servicio': servicio,
    }
    return render (request, 'servicios/servicio.html', context)
def editarServicio(request,id):
    edit_Servicio = Servicio.objects.get(id=id)
    servicio = ServicioForm(request.POST or None, request.FILES or None, instance=edit_Servicio)
    context = {
        'servicio': servicio,
    }
    if servicio.is_valid() and request.method == 'POST':
        servicio.save()
        return redirect('servicio')
    return render (request, 'servicios/servicio.html', context) 
     
def eliminarServicio(request,id):
    delete_Servicio = Servicio.objects.get(id=id)
    url_back = 'servicio'
    txt_action = 'Servicio'
    context = {
        'url_back': url_back,
        'txt_action': txt_action,
    }
    if request.method == 'POST':
        delete_Servicio.delete()
        return redirect ('servicio')  
    return render (request, 'servicios/deleteServicio.html',context)
# lOGICA DE insumo (EDITAR ELIMINAR Y OTRAS FUNCIONES)
@login_required(login_url='/login/')
def insumo(request):
    #recorrer datos de la base de datos
    insumo_db = Insumo.objects.all()
    marca_db = Marca.objects.all()
    
    #formularios
    marca = MarcaForm(request.POST or None)
    insumo = InsumoForm(request.POST or None, request.FILES or None)
    #validar formularios
    if insumo.is_valid() and request.method == 'POST':
        insumo.save()
        return redirect('insumo')
    if marca.is_valid() and request.method == 'POST':
        marca.save()
        messages.success(request,'Marca creada correctamente')
        return redirect('insumo')
    #
    context = {
        'insumo_db': insumo_db,	
        'insumo': insumo,
        'marcas': marca_db,
        'marca': marca,
    }
    return render (request, 'servicios/insumo.html', context)

def editarInsumo(request,id):
    edit_insumo = Insumo.objects.get(id=id)
    insumo = InsumoForm(request.POST or None, request.FILES or None, instance=edit_insumo)
    context = {
        'insumo': insumo,
    }
    if insumo.is_valid() and request.method == 'POST':
        insumo.save()
        return redirect('insumo')
    return render (request, 'servicios/insumo.html', context) 
     
def eliminarInsumo(request,id):
    delete_insumo = Insumo.objects.get(id=id)
    url_back = 'insumo'
    txt_action = 'insumo'
    context = {
        'url_back': url_back,
        'txt_action': txt_action,
    }
    if request.method == 'POST':
        delete_insumo.delete()
        return redirect ('insumo')  
    return render (request, 'servicios/deleteinsumo.html',context)

# LOGICA DE marca (EDITAR, ELIMINAR  Y OTRAS FUNCIONES)
@login_required(login_url='/login/')
def marca(request):
    marca_db = Marca.objects.all()
    marca = MarcaForm(request.POST or None)
    if marca.is_valid():
        marca.save()
        return redirect('marca')
    context = {
        'marca_dbs': marca_db,
        'marca': marca,
    }
    return render (request,'servicios/marca.html', context)


def editarMarca(request,id):
    edit_marca = Marca.objects.get(id=id)
    marca = MarcaForm(request.POST or None, instance=edit_marca)
    context={
        'marca': marca,
    }
    if marca.is_valid() and request.method == 'POST':
        marca.save()
        return redirect('marca')
    return render (request, 'servicios/marca.html', context)   

def eliminarMarca(request,id):
    delete_marca = Marca.objects.get(id=id)
    url_back = 'marca'
    txt_action = 'marca'
    context = {
        'url_back': url_back,
        'txt_action': txt_action,
    }
    if request.method == 'POST':
        delete_marca.delete()
        return redirect ('marca') 
    return render (request, 'servicios/deletemarca.html',context)

templates/servicios/deleteinsumo.html
{% include "servicios/insumo.html" %}
{% block body %}
{% block content %}


{% include 'modals/deleteinsumo.html' %}

{% endblock content %}
{% endblock body %}

templates/servicios/deletemarca.html
{% extends 'basepag.html' %}
{% block body %}
{% block content %}

{% include "servicios/marca.html" %}
{% include 'modals/deletemarca.html' %}

{% endblock content %}
{% endblock body %}

templates/servicios/deleteservicio.html
{% block body %}
{% block content %}

{% include "servicios/servicio.html" %}
{% include 'modals/deleteservicio.html' %}

{% endblock content %}
{% endblock body %}

templates/servicios/insumo.html
{% extends "basepag.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Insumo
{% endblock title  %}


{% block navbar %}
{% include "components/navbar.html" %}
{% endblock navbar %}

{% block body %}


{% block content %}


<div class="container flex flex-wrap justify-center gap-10 mx-auto overflow-hidden">

    <div
        class="w-full py-5 my-1 overflow-hidden sm:my-2 sm:px-2 sm:w-full md:my-1 md:px-1 md:w-1/2 lg:my-1 lg:px-1 lg:w-1/2 xl:my-2 xl:px-2 xl:w-1/2">
        <h1 class="px-2 mb-2 font-sans text-xl font-bold text-center break-normal dark:text-white lg:mt-0 md:text-2xl">
            Registro insumo</h1>
        <form enctype="multipart/form-data" name="form1" method="POST">
            {% csrf_token %}


            <div id="div_id_nombre" class="mb-3">
                <label for="id_nombre" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Nombre<span class="asteriskField">*</span> </label> <input type="text" name="nombre" maxlength="45"
                    class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none textinput focus:outline-none"
                    required="" id="id_nombre">
            </div>
            <div id="div_id_cantidad" class="mb-3"> <label for="id_cantidad"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Cantidad<span class="asteriskField">*</span> </label> <input type="number" name="cantidad" min="0"
                    class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none numberinput focus:outline-none"
                    required="" id="id_cantidad">
            </div>
            <div id="div_id_precioUnitario" class="mb-3"> <label for="id_precioUnitario"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Precio<span class="asteriskField">*</span> </label> <input type="number" name="precioUnitario"
                    value="0"
                    class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none numberinput focus:outline-none"
                    required="" id="id_precioUnitario">
            </div>
            <div id="div_id_marca" class="mb-3"> <label for="id_marca"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Marca<span class="asteriskField">*</span> </label>
                <div class="mb-3">
                    <div class="relative">
                        <select
                            class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none focus:outline-none"
                            name="marca">
                            <option selected disable="true" value="">---------</option>
                            {% for marcas in marcas %}
                            <option value="{{marcas.id}}">{{marcas.nombre}}</option>
                            {% endfor %}
                        </select>
                        {% csrf_token %}
                    </div>
                </div>
            </div>
            <div class="flex justify-center">
                <button type="submit"
                    class=" text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800"
                    value="Enviar informacion">
                    Agregar insumo
                </button>
        </form>


        <label for="my-modal-3"
            class="modal-button text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800">Agregar
            marca</label>

        <input type="checkbox" id="my-modal-3" class="modal-toggle">
        <div class="modal">
            <div class="relative modal-box">
                <label for="my-modal-3" class="absolute btn btn-sm btn-circle right-2 top-2">✕</label>
                <h3 class="text-lg font-bold">¿Olvidaste registrar una marca?</h3>
                <p class="py-4">Directamente puedes registrarla desde acá!</p>
                
                <form method="POST" name="form2">
                    {% csrf_token %}
                    <!-- <div id="div_id_nombre" class="mb-3"> <label for="id_nombre"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                            Nombre<span class="asteriskField">*</span> </label> <input type="text" name="nombre"
                            maxlength="45"
                            class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none textinput focus:outline-none"
                            required="" id="id_nombre">
                    </div>

                    <button type="submit" for="my-modal-3"
                        class="modal-button text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800">Agregar
                        marca</button> -->
                        {{marca|crispy}}
                        <button type="submit" for="my-modal-3"
                        class="modal-button text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800">Agregar
                        marca</button>
                </form>
            </div>
        </div>
    </div>

</div>

<div class="w-full px-1 my-1 overflow-hidden sm:w-full sm:my-2 sm:px-2 ">
    <!-- table -->
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-4 sm:px-6 lg:px-8">
            <div class="overflow-hidden">
                <table id="tabla" class="min-w-full text-sm text-left text-gray-500 rounded-sm dark:text-gray-400">
                    <thead
                        class="text-xs text-center text-gray-700 uppercase bg-light-white dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                Nombre
                            </th>
                            <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                Cantidad
                            </th>
                            <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                Marca
                            </th>
                            <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                precio
                            </th>
                            <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                Opciones
                            </th>
                        </tr>

                    </thead>
                    <tbody>
                        {% for insumo in insumo_db %}
                        <tr
                            class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">

                            <th scope="row"
                                class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                {{insumo.nombre}}
                            </th>
                            <td class="px-6 py-4">
                                {{insumo.cantidad }}
                            </td>
                            <td class="px-6 py-4">
                                {{insumo.marca }}
                            </td>
                            <td class="px-6 py-4">
                                {{insumo.precioUnitario }}
                            </td>

                            <td class="flex justify-around px-6 py-4 text-right">
                                {% comment %} Editar {% endcomment %}
                                <a href="{% url 'editarInsumo' insumo.id %}"
                                    class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500"><svg
                                        xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20"
                                        fill="currentColor">
                                        <path
                                            d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                                    </svg>
                                </a>
                                {% comment %} Eliminar {% endcomment %}
                                <a href="{% url 'eliminarInsumo' insumo.id %}">
                                    <button
                                        class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500 hover:underline"
                                        type="button" data-modal-toggle="popup-modal">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20"
                                            fill="currentColor">
                                            <path fill-rule="evenodd"
                                                d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

</div>








<!--Búsqueda-->

<!--Tabla-->
{% endblock content %}


{% endblock body %}

templates/servicios/marca.html
{% extends "basepag.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Marca
{% endblock title  %}


{% block navbar %}
{% include "components/navbar.html" %}
{% endblock navbar %}

{% block body %}
  

{% block content %}


<div class="container flex flex-wrap justify-center gap-10 mx-auto overflow-hidden">
    
    <div class="w-full py-5 my-1 overflow-hidden sm:my-2 sm:px-2 sm:w-full md:my-1 md:px-1 md:w-1/2 lg:my-1 lg:px-1 lg:w-1/2 xl:my-2 xl:px-2 xl:w-1/2">
                    <h1 class="px-2 mb-2 font-sans text-xl font-bold text-center break-normal dark:text-white lg:mt-0 md:text-2xl">
                        Registro marca</h1>
                    <!--Card-->
                  <!-- form -->
                  
                
                    
                    <form  enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                        {{marca|crispy}}
                        
                        <div class="flex justify-center">
                            <button type="submit"
                            class=" text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800"
                            value="Enviar informacion">
                            AGREGAR
                        </button>
                    </div>
                </form>
            
            </div>
               
              
                <div class="w-full px-1 my-1 overflow-hidden sm:w-full sm:my-2 sm:px-2 ">
                  <!-- table -->
                  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-4 sm:px-6 lg:px-8">
                        <div class="overflow-hidden">
                            <table id="tabla"
                                class="min-w-full text-sm text-left text-gray-500 rounded-sm dark:text-gray-400">
                                <thead
                                    class="text-xs text-center text-gray-700 uppercase bg-light-white dark:bg-gray-700 dark:text-gray-400">
                                    <tr>
                                        <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                            Nombre
                                        </th>
                                       
                                        
                                        <th scope="col" class="flex px-6 py-4 text-sm font-medium text-center text-black dark:text-gray">
                                            Opciones
                                        </th>



                                    </tr>

                                </thead>
                                <tbody>
                                    {% for marca in marca_dbs %}
                                    <tr
                                        class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                                        
                                        <th scope="row"
                                            class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                            {{marca.nombre}}
                                        </th>
                                       
                                        
                                        <td class="flex justify-around px-6 py-4 text-right">
                                            {% comment %} Editar {% endcomment %}
                                            <a href="{% url 'editarMarca' marca.id %}"
                                                class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500"><svg
                                                    xmlns="http://www.w3.org/2000/svg" class="w-5 h-5"
                                                    viewBox="0 0 20 20" fill="currentColor">
                                                    <path
                                                        d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                                                </svg>
                                            </a>
                                            {% comment %} Eliminar {% endcomment %}
                                            <a href="{% url 'eliminarMarca' marca.id %}">
                                            <button class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500 hover:underline" type="button" data-modal-toggle="popup-modal">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5"
                                                    viewBox="0 0 20 20" fill="currentColor">
                                                    <path fill-rule="evenodd"
                                                        d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                        clip-rule="evenodd" />
                                                </svg>
                                        </button>
                                    </a>
                                        </td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                </div>
              
              </div>





            
            

            <!--Búsqueda-->

            <!--Tabla-->
{% endblock content %}


{% endblock body %}

templates/servicios/servicio.html
{% extends "basepag.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Servicio
{% endblock title  %}


{% block navbar %}
{% include "components/navbar.html" %}
{% endblock navbar %}

{% block body %}
  

{% block content %}


<div class="container flex flex-wrap justify-center gap-10 mx-auto overflow-hidden">
    
    <div class="w-full py-5 my-1 overflow-hidden sm:my-2 sm:px-2 sm:w-full md:my-1 md:px-1 md:w-1/2 lg:my-1 lg:px-1 lg:w-1/2 xl:my-2 xl:px-2 xl:w-1/2">
                    <h1 class="px-2 mb-2 font-sans text-xl font-bold text-center break-normal dark:text-white lg:mt-0 md:text-2xl">
                        Registro Servicio</h1>
                    <!--Card-->
                  <!-- form -->
                  
                
                    
                    <form  enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                        {{ servicio|crispy}}
                        
                        <div class="flex justify-center">
                            <button type="submit"
                            class=" text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800"
                            value="Enviar informacion">
                            AGREGAR
                        </button>
                    </div>
                </form>
            
            </div>
               
              
                <div class="w-full px-1 my-1 overflow-hidden sm:w-full sm:my-2 sm:px-2 ">
                  <!-- table -->
                  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-4 sm:px-6 lg:px-8">
                        <div class="overflow-hidden">
                            <table id="tabla"
                                class="min-w-full text-sm text-left text-gray-500 rounded-sm dark:text-gray-400">
                                <thead
                                    class="text-xs text-center text-gray-700 uppercase bg-light-white dark:bg-gray-700 dark:text-gray-400">
                                    <tr>
                                        <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                            Tipo de Servicio
                                        </th>
                                        <th scope="col" class="flex px-6 py-4 text-sm font-medium text-center text-black">
                                            Opciones
                                        </th>



                                    </tr>

                                </thead>
                                <tbody>
                                    {% for servicio in servicio_db %}
                                    <tr
                                        class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                                        
                                        <th scope="row"
                                            class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                            {{servicio.tipodeservicio}}
                                        </th>
                                        <td class="flex justify-around px-6 py-4 text-right">
                                            {% comment %} Editar {% endcomment %}
                                            <a href="{% url 'editarServicio' servicio.id %}"
                                                class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500"><svg
                                                    xmlns="http://www.w3.org/2000/svg" class="w-5 h-5"
                                                    viewBox="0 0 20 20" fill="currentColor">
                                                    <path
                                                        d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                                                </svg>
                                            </a>
                                            {% comment %} Eliminar {% endcomment %}
                                            <a href="{% url 'eliminarServicio' servicio.id %}">
                                            <button class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500 hover:underline" type="button" data-modal-toggle="popup-modal">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5"
                                                    viewBox="0 0 20 20" fill="currentColor">
                                                    <path fill-rule="evenodd"
                                                        d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                        clip-rule="evenodd" />
                                                </svg>
                                        </button>
                                    </a>
                                        </td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                </div>
              
              </div>





            
            

            <!--Búsqueda-->

            <!--Tabla-->
{% endblock content %}


{% endblock body %}