core/urls.py
from django.contrib import admin
from django.urls import include, path
from core import views
from core.views import home, manual,error_404
from django.conf.urls import handler404, handler500
urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home, name='home'),
    path('registro/', include('registro.urls')),
    path('servicio/',include('servicios.urls')),
    path('factura/',include("facturacion.urls")),
    path('manual', views.manual, name=''), 
    path('backup/', views.backup, name = 'backup'),
    
]
handler404 = 'core.views.error_404'

registro/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.

    
class Usuario(models.Model):
    nombre = models.CharField(max_length=45, blank=False, unique= False, verbose_name=u"Nombre")
    apellido = models.CharField(max_length=45, blank=False, unique= False, verbose_name=u"Apellido")
    telefono = models.CharField(max_length=13, blank=True, unique=True, verbose_name="Numero de celular")

    def __str__(self) -> str:
        return '%s %s'%(self.nombre, self.apellido)

class Vehículo(models.Model):
    placa = models.CharField(max_length=7, unique=True,verbose_name="Placa")
    fecha = models.DateField(verbose_name="Fecha de Registro", auto_now_add=True)
    modelo = models.CharField(max_length=25)
    color= models.CharField(max_length=15, verbose_name="Color del vehículo")
    class Estado(models.TextChoices):
        EXCELENTE = 'E', _('Exelente (E)')
        REGULAR = 'R', _('Regular (R)')
        BIEN = 'B', _('Bien (B)')
        MAL = 'M', _('Mal (M)')
    estado = models.CharField(max_length=10,choices=Estado.choices, verbose_name=u"Estado")
    usuario=models.ForeignKey(Usuario,on_delete=models.SET_NULL, null=True,verbose_name=u"Usuario")
    
    def __str__(self) -> str:
        return '%s'%(self.placa)

templates/register/deleteUser.html
{% block body %}
{% block content %}

{% include "register/user.html" %}
{% include 'modals/deleteuser.html' %}

{% endblock content %}
{% endblock body %}

templates/register/deletevehicle.html
{% extends 'basepag.html' %}
{% block body %}
{% block content %}

{% include "register/user.html" %}
{% include 'modals/deletevehicle.html' %}

{% endblock content %}
{% endblock body %}

templates/register/user.html
{% extends "basepag.html" %}\
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Usuario {% endblock title %}
{% block navbar %}
{% include "components/navbar.html" %}
{% endblock navbar %}
{% block body %}
{% block content %}

<div class="container flex flex-wrap justify-center gap-10 mx-auto overflow-hidden">
    <div
        class="w-full py-5 my-1 overflow-hidden sm:my-2 sm:px-2 sm:w-full md:my-1 md:px-1 md:w-1/2 lg:my-1 lg:px-1 lg:w-1/2 xl:my-2 xl:px-2 xl:w-1/2">

        {% if messages %}    
        <div id="toast-default"
            class="flex items-center justify-center w-full p-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
            role="alert">
            <div
                class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-blue-500 bg-blue-100 rounded-lg dark:bg-blue-800 dark:text-blue-200">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z"
                        clip-rule="evenodd"></path>
                </svg>
                <span class="sr-only">Fire icon</span>
            </div>
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}" {% endif %} class="flex justify-center ml-3 text-sm font-normal">{{ message }}</div>
            {% endfor %}
            <button type="button"
                class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
                data-dismiss-target="#toast-default" aria-label="Close">
                <span class="sr-only">Close</span>
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                        clip-rule="evenodd"></path>
                </svg>
            </button>
        </div>
        {% endif %}

        <h1 class="px-2 mb-2 font-sans text-xl font-bold text-center break-normal dark:text-white lg:mt-0 md:text-2xl">
            Registro Usuario
        </h1>
        <!--Card-->
        <!-- form -->
        <form enctype="multipart/form-data" method="POST">

            <input type="hidden" name="csrfmiddlewaretoken"
                value="Bz4H8ZqcLL9aar8clUzq3MP5mkAz4lNcIqg1SL0EPCFM0C2GZyhBYGdN7OdOpjeA" />

            <div id="div_id_nombre" class="mb-3">
                <label for="id_nombre" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Nombre<span class="asteriskField">*</span>
                </label>
                <input type="text" value="{{edit.nombre}}" name="nombre" maxlength="45"
                    class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none textinput focus:outline-none"
                    required="" id="id_nombre" />
            </div>
            <div id="div_id_apellido" class="mb-3">
                <label for="id_apellido" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Apellido<span class="asteriskField">*</span>
                </label>
                <input type="text" name="apellido" value="{{edit.apellido}}" maxlength="45"
                    class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none textinput focus:outline-none"
                    required="" id="id_apellido" />
            </div>
            <div id="div_id_telefono" class="mb-3">
                <label for="id_telefono" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Numero de celular
                </label>
                <input type="text" name="telefono" value="{{edit.telefono}}" maxlength="13"
                    class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none textinput focus:outline-none"
                    id="id_telefono" />
            </div>

            <div class="flex justify-center">
                <button type="submit"
                    class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800"
                    value="Enviar informacion">
                    AGREGAR USUARIO
                </button>
                {% csrf_token %}
            </div>

        </form>
    </div>

    <div class="w-full px-1 my-1 overflow-hidden sm:w-full sm:my-2 sm:px-2">
        <!-- table -->
        <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-4 sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table id="tabla" class="min-w-full text-sm text-left text-gray-500 rounded-sm dark:text-gray-400">
                        <thead
                            class="text-xs text-gray-700 uppercase bg-light-white dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Nombre
                                </th>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Apellido
                                </th>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Telefono
                                </th>

                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Opciones
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for usuario in usuario_db %}
                            <tr
                                class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                                <th scope="row"
                                    class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                    {{usuario.nombre}}
                                </th>
                                <td class="px-6 py-4">{{usuario.apellido}}</td>
                                <td class="px-6 py-4">{{usuario.telefono}}</td>

                                <td class="flex justify-around px-6 py-4 text-right">
                                    {% comment %} Editar {% endcomment %}
                                    <a href="{% url 'editarUsuario' usuario.id %}" data-modal-toggle="popup-modal"
                                        class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500"><svg
                                            xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20"
                                            fill="currentColor">
                                            <path
                                                d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                                        </svg>
                                    </a>
                                    {% comment %} Eliminar {% endcomment %}
                                    <a href="{% url 'eliminarusuario' usuario.id %}">
                                        <button
                                            class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500 hover:underline"
                                            type="button" data-modal-toggle="popup-modal">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20"
                                                fill="currentColor">
                                                <path fill-rule="evenodd"
                                                    d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                    clip-rule="evenodd" />
                                            </svg>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Búsqueda-->

<!--Tabla-->
{% endblock content %} {% endblock body %}

templates/register/vehiculo.html
{% extends "basepag.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Vehiculo {% endblock title %}
{% block navbar %} {% include "components/navbar.html" %} {% endblock navbar %}
{% block content %}

<div class="container flex flex-wrap justify-center gap-10 mx-auto overflow-hidden">
    <div
        class="w-full py-5 my-1 overflow-hidden sm:my-2 sm:px-2 sm:w-full md:my-1 md:px-1 md:w-1/2 lg:my-1 lg:px-1 lg:w-1/2 xl:my-2 xl:px-2 xl:w-1/2">
        {% if messages %}    
        <div id="toast-default"
            class="flex items-center justify-center w-full p-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
            role="alert">
            <div
                class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-blue-500 bg-blue-100 rounded-lg dark:bg-blue-800 dark:text-blue-200">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z"
                        clip-rule="evenodd"></path>
                </svg>
                <span class="sr-only">Fire icon</span>
            </div>
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}" {% endif %} class="flex justify-center ml-3 text-sm font-normal">{{ message }}</div>
            {% endfor %}
            <button type="button"
                class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
                data-dismiss-target="#toast-default" aria-label="Close">
                <span class="sr-only">Close</span>
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                        clip-rule="evenodd"></path>
                </svg>
            </button>
        </div>
        {% endif %}
        <h1 class="px-2 mb-2 font-sans text-xl font-bold text-center break-normal dark:text-white lg:mt-0 md:text-2xl">
            Registrar Vehículo
        </h1>
        <form enctype="multipart/form-data" method="POST">
            <input type="hidden" name="csrfmiddlewaretoken"
                value="HocI7iYIaEkLqXnxy6y1fhQcRnAja02CFbar11oTvdzLh7nsQM6gETBN6TyWPl8o" />

            <div id="div_id_placa" class="mb-3">
                <label for="id_placa" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Placa<span class="asteriskField">*</span>
                </label>
                <input type="text" value="{{edit.placa}}" name="placa" maxlength="7"
                    class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none textinput focus:outline-none"
                    required="" id="id_placa" />
            </div>
            <div id="div_id_fecha" class="mb-3">
                <label for="id_fecha" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Fecha de Registro<span class="asteriskField">*</span>
                </label>
                <input type="date" value="{{edit.fecha}}" name="fecha" placeholder="Seleccione una fecha"
                    class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none dateinput focus:outline-none"
                    required="" id="id_fecha" />
            </div>
            <div id="div_id_modelo" class="mb-3">
                <label for="id_modelo" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Modelo<span class="asteriskField">*</span>
                </label>
                <input type="text" value="{{edit.modelo}}" name="modelo" maxlength="25"
                    class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none textinput focus:outline-none"
                    required="" id="id_modelo" />
            </div>
            <div id="div_id_color" class="mb-3">
                <label for="id_color" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Color del vehículo<span class="asteriskField">*</span>
                </label>
                <input type="text" value="{{edit.color}}" name="color" maxlength="15"
                    class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none textinput focus:outline-none"
                    required="" id="id_color" />
            </div>
            <div id="div_id_estado" class="mb-3">
                <label for="id_estado" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Estado<span class="asteriskField">*</span>
                </label>
                <div class="mb-3">
                    <div class="relative">
                        <select
                            class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none focus:outline-none"
                            name="estado">
                            <option value="">Seleccione estado del vehiculo</option>
                            <option value="E">Exelente (E)</option>
                            <option value="R">Regular (R)</option>
                            <option value="B">Bien (B)</option>
                            <option value="M">Mal (M)</option>
                        </select>
                    </div>
                </div>
            </div>
            <div id="div_id_usuario" class="mb-3">
                <label for="id_usuario" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">
                    Usuario<span class="asteriskField">*</span>
                </label>
                <div class="mb-3">
                    <div class="relative">
                        <select
                            class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none focus:outline-none"
                             name="usuario">
                            <option selected disable="true" value="">seleccione el vehiculo {{edit.usuario}}</option>
                            {% for usuario in usuario_db %}
                            <option value="{{usuario.id}}">{{usuario}}
                            </option>
                            {% endfor %}

                        </select>
                        {% csrf_token %}
                    </div>
                </div>
            </div>

            <div class="flex justify-center">
                <button type="submit"
                    class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800"
                    value="Enviar informacion">
                    AGREGAR
                </button>
            </div>
        </form>
    </div>

    <div class="w-full px-1 my-1 overflow-hidden sm:w-full sm:my-2 sm:px-2">
        <!-- table -->
        <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-4 sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table id="tabla" class="min-w-full text-sm text-left text-gray-500 rounded-sm dark:text-gray-400">
                        <thead
                            class="text-xs text-gray-700 uppercase bg-light-white dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Placa
                                </th>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Fecha
                                </th>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Modelo
                                </th>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Color
                                </th>

                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Estado
                                </th>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Usuario
                                </th>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Opciones
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for vehiculo in vehiculo_db %}
                            <tr
                                class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                                <th scope="row"
                                    class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                    {{vehiculo.placa}}
                                </th>
                                <td class="px-6 py-4">{{vehiculo.fecha}}</td>
                                <td class="px-6 py-4">{{vehiculo.modelo}}</td>
                                <td class="px-6 py-4">{{vehiculo.color}}</td>
                                <td class="px-6 py-4">{{vehiculo.estado}}</td>
                                <td class="px-6 py-4">{{vehiculo.usuario}}</td>
                                <td class="flex justify-around px-6 py-4 text-right">
                                    {% comment %} Editar {% endcomment %}
                                    <a href="{% url 'editarVehiculo' vehiculo.id %}"
                                        class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500"><svg
                                            xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20"
                                            fill="currentColor">
                                            <path
                                                d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                                        </svg>
                                    </a>
                                    {% comment %} Eliminar {% endcomment %}
                                    <a href="{% url 'eliminarvehiculo' vehiculo.id %}">
                                        <button
                                            class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500 hover:underline"
                                            type="button" data-modal-toggle="popup-modal">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20"
                                                fill="currentColor">
                                                <path fill-rule="evenodd"
                                                    d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                    clip-rule="evenodd" />
                                            </svg>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}