core/urls.py
from django.contrib import admin
from django.urls import include, path
from core import views
from core.views import home, manual,error_404
from django.conf.urls import handler404, handler500
urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home, name='home'),
    path('registro/', include('registro.urls')),
    path('servicio/',include('servicios.urls')),
    path('factura/',include("facturacion.urls")),
    path('manual', views.manual, name=''), 
    path('backup/', views.backup, name = 'backup'),
    
]
handler404 = 'core.views.error_404'

facturacion/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path ('factura/',views.factura, name='factura'),
    path('detallefactura/<int:pk>',views.detallefactura, name='detallefactura'),
    path('verfactura/<int:pk>/',views.viewFac, name='verfactura'),
    
    
    path ('factura/eliminarfactura/<int:id>',views.eliminarFactura, name='eliminarfactura'),
    path ('factura/editarfactura/<int:id>',views.editarFactura, name='editarFactura'),
]

facturacion/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from registro.models import Usuario, Vehículo
from servicios.models import Servicio,Insumo


class Factura(models.Model):    
    fecha=models.DateField(auto_now=True)
    Usuario=models.ForeignKey(Usuario,on_delete=models.SET_NULL, null=True,verbose_name='Usuario') 
    vehiculo = models.ForeignKey(Vehículo,on_delete=models.SET_NULL, null=True, verbose_name='Vehículo')
    class Estadofac(models.TextChoices):
        ACTIVO = 'Activo', _('Activa')
        FINAL = 'Finalizada', _('Finalizada')
    estado = models.CharField(max_length=11,choices=Estadofac.choices,default = Estadofac.ACTIVO, verbose_name=u"Estado")
    total = models.IntegerField(blank=True, default=0.00) 
    def __str__(self) -> str:
        return '%s %s %s'%(self.vehiculo,self.fecha, self.Usuario)

class detalleFactura(models.Model):
    total = models.IntegerField(blank=True, default=0.00)
    cantidad = models.IntegerField(default=0)
    
    factura = models.ForeignKey(Factura, on_delete=models.SET_NULL, null=True, verbose_name='Factura')
    servicio = models.ForeignKey(Servicio, on_delete=models.SET_NULL, null=True, verbose_name="servicio")
    insumo = models.ForeignKey(Insumo,on_delete=models.SET_NULL,null=True, verbose_name="Insumo")

    def __str__(self) -> str:
        return '%s %s'%(self.total, self.cantidad)

facturacion/forms.py
from dataclasses import field
from django import forms

from facturacion.models import Factura, detalleFactura

class FacturaForm(forms.ModelForm):
    class Meta:
        model = Factura
        fields = ['Usuario','vehiculo']
class DetalleForm(forms.ModelForm):
    class Meta:
        model = detalleFactura
        fields = ['servicio', 'insumo', 'total', 'cantidad']
        
            

facturacion/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.db import models
from facturacion.forms import DetalleForm, FacturaForm
from facturacion.models import Factura, detalleFactura
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Sum
from registro.models import Usuario, Vehículo
from servicios.models import Servicio,Insumo

from datetime import datetime

from servicios.models import Insumo


@login_required(login_url='/login/')
def factura(request):
    # logica 2 (prueba)
    factura_db = Factura.objects.all()
    usuarios = Usuario.objects.all()
    vehiculos = Vehículo.objects.all()
    time = datetime.now()

    if request.method == 'POST':
        factura = FacturaForm(request.POST)
        print(request.POST)
        if factura.is_valid():
            usuario = Usuario.objects.get(id=request.POST['Usuario'])
            vehiculo = Vehículo.objects.get(id=request.POST['vehiculo'])
            aux = Factura.objects.create(
                fecha=time.strftime("%d/%m/%y %H:%M:%S"),
                Usuario=usuario,
                vehiculo=vehiculo,
            )
            messages.success(request, f'Factura agregada corretamente.')
            print('se ah logrado hacer la factura ')

            return redirect('detallefactura', aux.id)
        else:
            print("formulario invalido")
    else:
        factura = FacturaForm()

    context = {
        'form': factura,
        'factura_db': factura_db,
        'usuario': usuarios,
        'vehiculo': vehiculos,
    }
    return render(request, 'facturacion/factura.html', context)

    #logica 1(funcional )############################
    # usuarios = Usuario.objects.all()              #
    # vehiculos = Vehículo.objects.all()
    #         factura.save()
    #         return redirect('factura')
    #     else:
    #         print("No es valido")
    # context = {
    #     'factura': factura_db,
    #     'factura_form': factura,
    #     'usuario': usuarios,
    #     'vehiculo': vehiculos,
    #############################################


def detallefactura(request, pk):  # pk es el id de la factura
    titulo_pagina = "facturas"
    detalles = detalleFactura.objects.filter(factura_id=pk)
    factura_u = Factura.objects.get(id=pk)

    servicio_db = Servicio.objects.all()
    insumo_db = Insumo.objects.all()
    
    
    # Suma los precios y da un total
    if(detalleFactura.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'), output_field=models.IntegerField()))):
        total = detalleFactura.objects.filter(factura_id=factura_u.id).values("factura").annotate(
            total_definitivo=Sum(('total'), output_field=models.IntegerField()))[0]["total_definitivo"]
    else:
        total = 0
    # Filtrando productos para visualizacion del cliente

    if request.method == 'POST':
        form= DetalleForm(request.POST)
        if form.is_valid():
            producto = Insumo.objects.get(id=request.POST['insumo'])
            if factura_u.estado == "Activo":
                existe = detalleFactura.objects.filter(
                    factura=pk, insumo_id=producto)
                if len(existe) == 0:
                    detalleFactura.objects.create(
                        cantidad=form.cleaned_data.get('cantidad'),
                        total=producto.precioUnitario *
                        form.cleaned_data.get('cantidad'),
                        factura=factura_u,
                        insumo=producto,
                    )
                    print('Parte uno')
                    print('********************* \n')
                    
                    Insumo.objects.filter(id=producto.id).update(
                        cantidad=producto.cantidad -
                        form.cleaned_data.get('cantidad')

                    )
                    print('Parte dos')
                    print('********************* \n')
                    if(detalleFactura.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'), output_field=models.IntegerField()))):
                        total = detalleFactura.objects.filter(factura_id=factura_u.id).values("factura").annotate(
                            total_definitivo=Sum(('total'), output_field=models.IntegerField()))[0]["total_definitivo"]
                        Factura.objects.filter(id=pk).update(
                            total=total
                        )
                    else:
                        total = 0

                    messages.success(
                        request, f' se agregó {producto} a la factura correctamente!')
                    return redirect('verfactura', pk=pk)
                else:
                    anterior = detalleFactura.objects.filter(
                        factura_id=pk, insumo_id=request.POST['insumo'])

                    detalleFactura.objects.filter(factura_id=pk, insumo_id=request.POST['insumo']).update(
                        cantidad=anterior[0].cantidad +
                        form.cleaned_data.get('cantidad'),
                        total=anterior[0].total + producto.precioUnitario *
                        form.cleaned_data.get('cantidad'),
                    )

                    Insumo.objects.filter(id=producto.id).update(
                        cantidad=producto.cantidad-
                        form.cleaned_data.get('cantidad')

                    )
                    if(detalleFactura.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'), output_field=models.IntegerField()))):
                        total = detalleFactura.objects.filter(factura_id=factura_u.id).values("factura").annotate(
                            total_definitivo=Sum(('total'), output_field=models.IntegerField()))[0]["total_definitivo"]
                        Factura.objects.filter(id=pk).update(
                            total=total
                        )
                    else:
                        total = 0

                    Factura.objects.filter(id=pk).update(
                        total=total
                    )

            else:
                if(producto.cantidad >= int(request.POST['cantidad'])):
                    existe = detalleFactura.objects.filter(
                        factura_id=factura_u.id, producto=producto)
                    cantidadA = Usuario.objects.filter(id=factura_u)
                    print(cantidadA)
                    if len(existe) == 0:

                        factura = detalleFactura.objects.create(
                            cantidad=form.cleaned_data.get('cantidad'),
                            total=producto.precioUnitario *
                            form.cleaned_data.get('cantidad'),
                            factura=factura_u,
                            insumo=producto,
                        )

                        Insumo.objects.filter(id=producto.id).update(
                            stock=producto.stock -
                            form.cleaned_data.get('cantidad')

                        )

                        if(detalleFactura.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'), output_field=models.IntegerField()))):
                            total = detalleFactura.objects.filter(factura_id=factura_u.id).values("factura").annotate(
                                total_definitivo=Sum(('total'), output_field=models.IntegerField()))[0]["total_definitivo"]
                            Factura.objects.filter(id=pk).update(
                                total=total
                            )
                        else:
                            total = 0

                        messages.success(
                            request, f' se agregó {producto} a la factura correctamente!')
                        return redirect('factura-detalle', pk=pk)
                    else:
                        anterior = detalleFactura.objects.filter(
                            factura_id=factura_u.id, producto=request.POST['insumo'])

                        anterior.update(
                            cantidad=anterior[0].cantidad -
                            form.cleaned_data.get('cantidad'),
                            total=anterior[0].total + producto.precioUnitario *
                            form.cleaned_data.get('cantidad'),
                        )
                        Insumo.objects.filter(id=producto.id).update(
                            stock=producto.stock -
                            form.cleaned_data.get('cantidad')
                        )
                        if(detalleFactura.objects.filter(factura_id=factura_u.id).values("factura").annotate(total_definitivo=Sum(('total'), output_field=models.IntegerField()))):
                            total = detalleFactura.objects.filter(factura_id=factura_u.id).values("factura").annotate(
                                total_definitivo=Sum(('total'), output_field=models.IntegerField()))[0]["total_definitivo"]
                            Factura.objects.filter(id=pk).update(
                                total=total
                            )
                        else:
                            total = 0
                else:
                    messages.warning(
                        request, f' Solo hay stock de {producto.stock} {producto.nombre}/s')
        else:
            messages.warning(request, f' Error')
    else:
        form = DetalleForm()
    context = {
        "titulo_pagina": titulo_pagina,
        "detalles": detalles,
        "form": form,
        "factura": factura_u,
        "total": total,
        "servicios": servicio_db,
        "insumos":  insumo_db,
    }
    return render(request, "facturacion/detalle.html", context)

templates/facturacion/deletefactura.html
{% extends 'basepag.html' %}
{% block body %}
{% block content %}

{% include "facturacion/factura.html" %}
{% include 'modals/deletefactura.html' %}

{% endblock content %}
{% endblock body %}

templates/facturacion/detalle.html
{% extends "basepag.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Factura
{% endblock title  %}


{% block navbar %}
{% include "components/navbar.html" %}
{% endblock navbar %}

{% block body %}


{% block content %}

<div>
    <!-- <form action="" method="POST">
        {% csrf_token %}
        {{form|crispy}}
    </form> -->

    <!-- formulario modificado -->
    <form action="" method="POST">
        {% csrf_token %}


        <!-- servicios -->
        <div id="div_id_servicio" class="mb-3"> <label for="id_servicio"
                class="block text-gray-700 text-sm font-bold mb-2">
                Servicio<span class="asteriskField">*</span> </label>
            <div class="mb-3">
                <div class="relative">
                    <select
                        class="bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700"
                        name="servicio">
                        <option value="">---------</option>
                        {% for servicio in servicios %}
                        <option value="{{servicio.id}}">{{servicio.tipodeservicio}}</option>  
                        {% endfor %}
                    </select>
                   
                </div>
            </div>
        </div>


        <!-- insumo -->

        <div id="div_id_insumo" class="mb-3"> <label for="id_insumo" class="block text-gray-700 text-sm font-bold mb-2">
                Insumo<span class="asteriskField">*</span> </label>
            <div class="mb-3">
                <div class="relative">
                    <select
                        class="bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700"
                        name="insumo">
                        <option value="">---------</option>
                        {% for insumo in insumos  %}
                        <option value="{{insumo.id}}">{{insumo.nombre}} {{insumo.cantidad}}</option> 
                        {% endfor %}
                    </select>
                    
                </div>
            </div>
        </div>


        <div id="div_id_total" class="mb-3"> <label for="id_total" class="block text-gray-700 text-sm font-bold mb-2">
                Total
            </label><input type="text" id="disabled-input" aria-label="{{total}}" class="mb-6 bg-gray-100 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 cursor-not-allowed dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500" value="{{total}}" disabled>
            </div>


        <div id="div_id_cantidad" class="mb-3"> <label for="id_cantidad"
                class="block text-gray-700 text-sm font-bold mb-2">
                Cantidad<span class="asteriskField">*</span> </label> <input type="number" name="cantidad" value="21"
                class="numberinput rounded-lg py-2 border-gray-300 appearance-none w-full bg-white block leading-normal px-4 text-gray-700 focus:outline-none border"
                required="" id="id_cantidad"> </div>

        <button class="btn btn-success">enviar</button>
    </form>


</div>
{% endblock content %}
{% endblock body %}

templates/facturacion/detallefactura.html
{% extends 'basepag.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Detalle factura
{% endblock title  %}

{% block content %}
hola mundo
{% endblock content %}

templates/facturacion/factura.html
{% extends "basepag.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Factura
{% endblock title  %}


{% block navbar %}
{% include "components/navbar.html" %}
{% endblock navbar %}

{% block body %}


{% block content %}
<div class="container flex flex-wrap justify-center gap-10 mx-auto overflow-hidden">
    <div class="container flex flex-wrap justify-center gap-10 mx-auto overflow-hidden">
        <div
            class="w-full py-5 my-1 overflow-hidden sm:my-2 sm:px-2 sm:w-full md:my-1 md:px-1 md:w-1/2 lg:my-1 lg:px-1 lg:w-1/2 xl:my-2 xl:px-2 xl:w-1/2">
            <h1
                class="px-2 mb-2 font-sans text-xl font-bold text-center break-normal dark:text-white lg:mt-0 md:text-2xl">
                Factura</h1>

            {% comment %} {% csrf_token %}
            <div id="div_id_Usuario" class="mb-3">
                <label for="id_Usuario" class="block mb-2 text-sm font-bold text-black">
                    Usuario<span class="asteriskField">*</span> </label>
                <div class="mb-3">
                    <div class="relative">
                        <select
                            class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none focus:outline-none select1"
                            name="Usuario">
                            <option selected disable="true">---------</option>
                            {% for user in usuario  %}
                            <option value="{{user.id}}">{{user.nombre}}</option>
                            {% endfor %}
                        </select>
                        <div
                            class="absolute inset-y-0 right-0 flex items-center px-2 text-gray-700 pointer-events-none">
                            <svg class="w-4 h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z">
                                </path>
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
            <div id="div_id_vehiculo" class="mb-3"> <label for="id_vehiculo"
                    class="block mb-2 text-sm font-bold text-gray-700">
                    Vehículo<span class="asteriskField">*</span> </label>
                <div class="mb-3">
                    <div class="relative">
                        <select
                            class="block w-full px-4 py-2 leading-normal text-gray-700 bg-white border border-gray-300 rounded-lg appearance-none focus:outline-none select2"
                            name="Vehiculo">
                            <option selected disable="true">---Seleccione la placa:---</option>
                            {% for vehicu in vehiculo %}
                            <option data-index-number="{{vehicu.usuario_id}}" value="{{vehicu.id}}">{{vehicu.placa}}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="flex justify-center">
                <button type="submit" for="my-modal-3" value="Abrir factura"
                    class="modal-button text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800">Generar
                    factura</button>
            </div>
            {% endcomment %}
            <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <div class="flex justify-center">
                <button type="submit" for="my-modal-3" value="Abrir factura"
                class="modal-button text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-600 dark:focus:ring-blue-800">Generar
                factura</button>
            </div>
            </form>
        </div>
    </div>
    <div class="w-full px-1 my-1 overflow-hidden sm:w-full sm:my-2 sm:px-2">

        <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-4 sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <table id="tabla" class="min-w-full text-sm text-left text-gray-500 rounded-sm dark:text-gray-400">
                        <thead
                            class="text-xs text-gray-700 uppercase bg-light-white dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Fecha
                                </th>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Vehiculo
                                </th>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    estado
                                </th>
                                <th scope="col" class="px-6 py-4 text-sm font-medium text-black">
                                    Opciones
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for fac in factura_db %}
                            <tr
                                class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">

                                <th scope="row"
                                    class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                                    {{fac.fecha}}
                                </th>
                                <td class="px-6 py-4">
                                    {{fac.vehiculo}}
                                </td>
                                <td class="px-6 py-4">
                                    {{fac.estado}}
                                </td>
                                <td class="flex justify-around px-6 py-4 text-right">
                                    {% comment %} Editar {% endcomment %}
                                    <a href="{% url 'editarFactura' fac.id %}"
                                        class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500"><svg
                                            xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20"
                                            fill="currentColor">
                                            <path
                                                d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                                        </svg>
                                    </a>
                                    {% comment %} Eliminar {% endcomment %}
                                    <a href="{% url 'eliminarfactura' fac.id %}">
                                        <button
                                            class="font-medium text-light-white md:hover:text-blue-700 dark:text-blue-500 hover:underline"
                                            type="button" data-modal-toggle="popup-modal">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20"
                                                fill="currentColor">
                                                <path fill-rule="evenodd"
                                                    d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                                                    clip-rule="evenodd" />
                                            </svg>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
</div>
</div>
{% endblock content %}
{% endblock body %}